# Generated by Django 5.0.8 on 2025-11-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oppia', '0054_cohort_criteria'),
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='trainings', to='oppia.course'),
        ),
    ]
